UPDATE ALUMNO
SET NOMBRE='JUAN ABREU'
WHERE id_alumno=5;

UPDATE ALUMNO
SET NOMBRE='PERENCEJO MALDITAMADRE'
WHERE fechanac=('31/10/14') AND ID_ALUMNO NOT IN (001,002,005);

ALTER TABLE ALUMNO 
ADD ESTADO CHAR(1);

ALTER TABLE ALUMNO
ADD CONSTRAINT ESTADO CHECK(ESTADO IN('A','I'));

UPDATE ALUMNO
SET ESTADO='A';

DELETE FROM ALUMNO
WHERE ID_ALUMNO=001;

SELECT *
FROM ALUMNO;

SELECT A.NOMBRE, C.DESCRIPCION
FROM ALUMNO A, CURSOS C
WHERE A.ID_CURSO=C.ID_CURSO AND (A.NOMBRE LIKE 'D%' 
OR A.FECHANAC BETWEEN '01/01/1990' AND '31/10/2014');

SELECT C.DESCRIPCION, A.ID_ASIGNATURA, A.DESCRIPCION, AL.NOMBRE
FROM CURSOS C, ASIGNATURA A, CURSO_ASIGNATURA B, ALUMNO AL
WHERE (C.ID_CURSO=B.ID_CURSO) AND (B.ID_ASIGNATURA=A.ID_ASIGNATURA) AND (AL.ID_CURSO=C.ID_CURSO);

SELECT * 
FROM ALUMNO A
WHERE EXISTS(SELECT *
FROM CURSOS C
WHERE C.ID_CURSO=A.ID_CURSO);

SELECT * 
FROM ALUMNO A
WHERE EXISTS(SELECT *
FROM CURSOS C
WHERE C.ID_CURSO=A.ID_CURSO AND ID_CURSO between 1 AND 6
AND FECHANAC between '01/11/1990' AND '01/12/2014');

SELECT COUNT (A.ID_CURSO), C.ID_CURSO, C.DESCRIPCION 
FROM CURSOS C, ALUMNO A
WHERE A.ID_CURSO=C.ID_CURSO
GROUP BY C.ID_CURSO, C.DESCRIPCION;
/*PRECENTA LA SUMATORIA DE ALUMNO QUE ESTAN EN CADA CURSO*/
SELECT DESCRIPCION, COUNT(A.ID_CURSO)
FROM ALUMNO A, CURSOS C
WHERE C.ID_CURSO=A.ID_CURSO
GROUP BY DESCRIPCION
ORDER BY COUNT(A.ID_CURSO)DESC;
/*PRECENTA LA EDAD MINICAM Y LA EDAD MAXIMA DE ESTUDIANTES QUE ESTAN EN TODOS LOS CURSOS*/
SELECT  MAX(ROUND((SYSDATE-FECHANAC)/365))AS "MAYOR EDAD",/*AS "MAYOR", ES PARA DARLE UN NOMBRE ALA COLUMNA A PRECENTAR*/
MIN(ROUND((SYSDATE-FECHANAC)/365))AS "MENOR EDAD" /*ROUND SIRVE PARA REDONDEAR*/
FROM ALUMNO;
/*PRESENTA EL MINIMO EL MAXIMO Y AVERAGE DE LAS EDADES DE CADA CURSO*/
SELECT C.DESCRIPCION, MAX(ROUND((SYSDATE-FECHANAC)/365))MAYOR,
MIN(ROUND((SYSDATE-FECHANAC)/365))MENOR,
COUNT(A.ID_CURSO)CANT_ALUMNO,
AVG(ROUND((SYSDATE-FECHANAC)/365))PROMEDIO_EDAD
FROM ALUMNO A, CURSOS C
WHERE A.ID_CURSO=C.ID_CURSO
GROUP BY C.DESCRIPCION;

SELECT GENERO, COUNT(*)
FROM PROFESOR
GROUP BY GENERO;
/*CANTIDAD DE AAIGNATURA QUE TIENE UN CURSO Y QUE EL CURSO COMIENCE CON B*/
SELECT C.DESCRIPCION,COUNT(CUR.ID_ASIGNATURA)
FROM ASIGNATURA A, CURSOS C,CURSO_ASIGNATURA CUR
WHERE A.ID_ASIGNATURA=CUR.ID_ASIGNATURA AND C.DESCRIPCION LIKE('B%')
GROUP BY C.DESCRIPCION;
