--------------------------------------------------------
--  File created - Wednesday-December-03-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PERSONAS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"EDAD" NUMBER, 
	"MES_NACIMIENTO" VARCHAR2(50 BYTE), 
	"UNIVERSIDAD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PERSONAS
SET DEFINE OFF;
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (1,'ALEXANDRO ABREU',20,'JUNIO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (2,'WILSON ACEVEDO',20,'ENERO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (3,'ESTELA ABREU',19,'FEBRERO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (4,'PEDRO ROSARIO',20,'ABRIL','UNPHU');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (5,'ANDY DANIEL',18,'MAYO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (6,'LEONEL FERNANDEZ',21,'JULIO','UNPHU');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (7,'ARISTIDES CRUZ',22,'MARZO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (8,'PEDRO ARISTIDES',24,'MARZO','UCATECI');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (9,'FFERNANDEZ FERNANDEZ',22,'ENERO','UNPHU');
Insert into PERSONAS (ID,NOMBRE,EDAD,MES_NACIMIENTO,UNIVERSIDAD) values (10,'CARLITOS FRAGANCIA',20,'FEBRERO','UCATECI');
