#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <string.h>

char unidad[]={"NULL", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve"};
char decena[]={"NULL", "diez", "veinte", "treinta", "cuarenta", "cincuenta", "sesenta", "setenta", "ochenta", "noventa"};
char diezvar[]={"NULL", "once", "doce", "trece", "catorce", "quince"};
char centena[]={"NULL", "ciento", "NULL", "NULL", "NULL", "quiniento", "NULL", "seteciento", "NULL", "noveciento"};
char milesima[]={"NULL", "mil", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL"};


