/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package segundoparcial20130253;

/**
 *
 * @author Entrenamiento
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        BotonPunto = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonMult = new javax.swing.JButton();
        BotonDiv = new javax.swing.JButton();
        BotonResultado = new javax.swing.JButton();
        BotonPorc = new javax.swing.JButton();
        BotonRC = new javax.swing.JButton();
        Pantalla = new javax.swing.JTextField();
        BotonBorrar1 = new javax.swing.JButton();
        BotonCE = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        BotonNeg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton4.setText("4");
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton4MouseClicked(evt);
            }
        });

        Boton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton5.setText("5");
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
        });

        Boton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton6.setText("6");
        Boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton6MouseClicked(evt);
            }
        });

        Boton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton3.setText("3");
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3MouseClicked(evt);
            }
        });

        Boton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton2.setText("2");
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
        });

        Boton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton1.setText("1");
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
        });
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton9.setText("9");
        Boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton9MouseClicked(evt);
            }
        });

        Boton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton8.setText("8");
        Boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton8MouseClicked(evt);
            }
        });

        Boton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton7.setText("7");
        Boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton7MouseClicked(evt);
            }
        });
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        BotonPunto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonPunto.setText(".");
        BotonPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPuntoMouseClicked(evt);
            }
        });

        Boton0.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton0.setText("0");
        Boton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton0MouseClicked(evt);
            }
        });
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });

        BotonSuma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSumaMouseClicked(evt);
            }
        });

        BotonResta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonResta.setText("-");
        BotonResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRestaMouseClicked(evt);
            }
        });

        BotonMult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonMult.setText("*");
        BotonMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMultMouseClicked(evt);
            }
        });

        BotonDiv.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonDiv.setText("/");
        BotonDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDivMouseClicked(evt);
            }
        });

        BotonResultado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonResultado.setText("=");
        BotonResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonResultadoMouseClicked(evt);
            }
        });

        BotonPorc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonPorc.setText("%");
        BotonPorc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPorcMouseClicked(evt);
            }
        });

        BotonRC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonRC.setText("RC");
        BotonRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRCMouseClicked(evt);
            }
        });
        BotonRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRCActionPerformed(evt);
            }
        });

        Pantalla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        BotonBorrar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonBorrar1.setText("<---");
        BotonBorrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBorrar1MouseClicked(evt);
            }
        });
        BotonBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrar1ActionPerformed(evt);
            }
        });

        BotonCE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonCE.setText("CE");
        BotonCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCEMouseClicked(evt);
            }
        });

        BotonC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonC.setText("C");
        BotonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCMouseClicked(evt);
            }
        });

        BotonNeg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BotonNeg.setText("+-");
        BotonNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonNegMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pantalla)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BotonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BotonResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPorc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRCActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton0ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1ActionPerformed

    public double Numero1 = 0;
    public double Numero2 = 0;
    public char op;
    
    
    private void Boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton7MouseClicked
      Pantalla.setText(Pantalla.getText() + "7");
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton7MouseClicked

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
       Pantalla.setText(Pantalla.getText() + "1");
    }//GEN-LAST:event_Boton1MouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        Pantalla.setText(Pantalla.getText() + "2");
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseClicked
        Pantalla.setText(Pantalla.getText() + "3");
    }//GEN-LAST:event_Boton3MouseClicked

    private void Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseClicked
        Pantalla.setText(Pantalla.getText() + "4");
    }//GEN-LAST:event_Boton4MouseClicked

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked
        Pantalla.setText(Pantalla.getText() + "5");
    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton6MouseClicked
        Pantalla.setText(Pantalla.getText() + "6");
    }//GEN-LAST:event_Boton6MouseClicked

    private void Boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton8MouseClicked
        Pantalla.setText(Pantalla.getText() + "8");
    }//GEN-LAST:event_Boton8MouseClicked

    private void Boton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton9MouseClicked
        Pantalla.setText(Pantalla.getText() + "9");
    }//GEN-LAST:event_Boton9MouseClicked

    private void BotonPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPuntoMouseClicked
        Pantalla.setText(Pantalla.getText() + "."); //Validar para no poner mas de un punto
    }//GEN-LAST:event_BotonPuntoMouseClicked

    private void Boton0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton0MouseClicked
        Pantalla.setText(Pantalla.getText() + "0");
    }//GEN-LAST:event_Boton0MouseClicked
        Funciones fun = new Funciones();
    private void BotonSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSumaMouseClicked
        if (Numero1 == 0){
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText("");
        }
        else
        {
            Numero2 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Suma(Numero1, Numero2))); //ejecutar metodo suma
            Numero1 = Numero2;
            Numero2 = 0;
        }        
        op = '+';
    }//GEN-LAST:event_BotonSumaMouseClicked

    private void BotonRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRestaMouseClicked
       if (Numero1 == 0){
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText("");
        }
        else
        {
            Numero2 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Resta(Numero1, Numero2)));
            /*Numero1 = Numero2;
            Numero2 = 0;*/           
        }      
       op = '-';
    }//GEN-LAST:event_BotonRestaMouseClicked

    private void BotonMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultMouseClicked
        if (Numero1 == 0){
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText("");
        }
        else
        {
            Numero2 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Mult(Numero1, Numero2)));
           /* = Numero2;
            Numero2 = 0;*/
        }      
        op = '*';
    }//GEN-LAST:event_BotonMultMouseClicked

    private void BotonBorrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrar1MouseClicked
        //Borrar primer caracter 
        Pantalla.setText(Pantalla.getText().substring(0,Pantalla.getText().length() - 1));
        
    }//GEN-LAST:event_BotonBorrar1MouseClicked

    private void BotonBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrar1ActionPerformed
       // TODO add your handling  code here:
    }//GEN-LAST:event_BotonBorrar1ActionPerformed

    private void BotonCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCEMouseClicked
        Numero1 = 0;
        Numero2 = 0;
        Pantalla.setText("");
    }//GEN-LAST:event_BotonCEMouseClicked

    private void BotonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCMouseClicked
        Pantalla.setText("");
    }//GEN-LAST:event_BotonCMouseClicked

    private void BotonNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNegMouseClicked
        Pantalla.setText("-" + Pantalla.getText());
    }//GEN-LAST:event_BotonNegMouseClicked

    private void BotonDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDivMouseClicked
        if (Numero1 == 0){
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText("");
        }
        else
        {
            Numero2 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Div(Numero1, Numero2)));
           /* = Numero2;
            Numero2 = 0;*/
        }      
        op = '/';
    }//GEN-LAST:event_BotonDivMouseClicked

    private void BotonRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRCMouseClicked
        
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Root(Numero1)));
           /* = Numero2;
            Numero2 = 0;*/
              
        op = 'R';
    }//GEN-LAST:event_BotonRCMouseClicked

    private void BotonPorcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPorcMouseClicked
        if (Numero1 == 0){
            Numero1 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText("");
        }
        else
        {
            Numero2 = Double.parseDouble(Pantalla.getText());
            Pantalla.setText(String.valueOf(fun.Porc(Numero1,Numero2)));
           /* = Numero2;
            Numero2 = 0;*/
        }     
        op = '%';
    }//GEN-LAST:event_BotonPorcMouseClicked

    private void BotonResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonResultadoMouseClicked
        Numero2 = Double.parseDouble(Pantalla.getText());
        Pantalla.setText(String.valueOf(fun.Igual(Numero1, op, Numero2)));
    }//GEN-LAST:event_BotonResultadoMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBorrar1;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonCE;
    private javax.swing.JButton BotonDiv;
    private javax.swing.JButton BotonMult;
    private javax.swing.JButton BotonNeg;
    private javax.swing.JButton BotonPorc;
    private javax.swing.JButton BotonPunto;
    private javax.swing.JButton BotonRC;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonResultado;
    private javax.swing.JButton BotonSuma;
    public javax.swing.JTextField Pantalla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
                                                                                            