ALTER TABLE CINE ADD CONSTRAINT FK_CIUDAD FOREIGN KEY (ID_CIUDAD) references CIUDADES (ID_CIUDAD);
ALTER TABLE SALAS ADD CONSTRAINT FK_CINE FOREIGN KEY (ID_CINE) references CINE (ID_CINE);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_SALA FOREIGN KEY (SALA_PROGRAMADA) references SALAS (ID_SALA);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_PELICULAS FOREIGN KEY (CONTENIDO_PROGRAMADO) references PELICULAS (ID_PELICULA);
ALTER TABLE CIUDADES ADD CONSTRAINT FK_PROVINCIA FOREIGN KEY (ID_PROVINCIA) references PROVINCIAS (ID_PROVINCIA);

