 gotoxy(30,5);
 Writeln('                            ___________                 ');
 gotoxy(30,6);
Writeln('                           /  |     |  \                ');
gotoxy(30,7);
Writeln('                          |   |     |   |               ');
gotoxy(30,8);
Writeln('                          |   |     |   |               ');
gotoxy(30,9);
Writeln('                          |   |     |   |               ');
gotoxy(30,10);
Writeln('                          |   |     |   |               ');
gotoxy(30,11);
Writeln('                          |=============|               ');
gotoxy(30,12);
Writeln('                          |   |     |   |               ');
gotoxy(30,13);
Writeln('                          |   |     |   |               ');
gotoxy(30,14);
Writeln('                          |   |     |   |               ');
gotoxy(30,15);
Writeln('                          |   |     |   |               ');
gotoxy(30,16);
Writeln('                          |=============|               ');
gotoxy(30,17);
Writeln('                          |   |     |   |               ');
gotoxy(30,18);
Writeln('                          |   |     |   |               ');
gotoxy(30,19);
Writeln('                          |   |     |   |               ');
gotoxy(30,20);
Writeln('                          |   |     |   |               ');
gotoxy(30,21);
Writeln('                          |=============|               ');
gotoxy(30,22);
Writeln('                          |   |     |   |               ');
gotoxy(30,23);
Writeln('                          |   |  _  |   |               ');
gotoxy(30,24);
Writeln('                          |   | | | |   |               ');
gotoxy(30,25);
Writeln('                          |___|_|_|_|___|               ');