--------------------------------------------------------
-- Archivo creado  - viernes-junio-20-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARRERA
--------------------------------------------------------

  CREATE TABLE "12-1993"."CARRERA" 
   (	"COD_CARRERA" VARCHAR2(3 BYTE), 
	"DESC_CARRERA" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANT
--------------------------------------------------------

  CREATE TABLE "12-1993"."ESTUDIANT" 
   (	"MATRICULA" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"CEDULA" VARCHAR2(11 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"SEXO" VARCHAR2(1 BYTE), 
	"COD_CARRERA" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into "12-1993".CARRERA
SET DEFINE OFF;
Insert into "12-1993".CARRERA (COD_CARRERA,DESC_CARRERA) values ('ISC','ING. EN SISTEMAS');
Insert into "12-1993".CARRERA (COD_CARRERA,DESC_CARRERA) values ('MED','MEDICINA');
Insert into "12-1993".CARRERA (COD_CARRERA,DESC_CARRERA) values ('INN','INDUSTRIAL');
Insert into "12-1993".CARRERA (COD_CARRERA,DESC_CARRERA) values ('ICI','CIVIL');
REM INSERTING into "12-1993".ESTUDIANT
SET DEFINE OFF;
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20121993','Willson Neriz','Acevedo Sanchez','0','La Loteria calle G casa#7','M','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20130253','Pedro Alberto','Rosario Estrella','1','calle club rotario #10','M','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20121345','Juan','Ramirez','3','las maras','F','ICI');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20124568','Tereza','Perez','4','barrio X','F','INN');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20134114','Alberto','Cruz','5','San Jose','M','ICI');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20127894','Juliana','Jarabe',null,null,'F','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('20131155','Karina','Palo',null,null,'M','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('2201456','William','Mana',null,null,'F','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('12854','Roberto','Rodriguez',null,null,'M','ISC');
Insert into "12-1993".ESTUDIANT (MATRICULA,NOMBRE,APELLIDO,CEDULA,DIRECCION,SEXO,COD_CARRERA) values ('216543','Carlos','Mendez',null,null,'M','ISC');
--------------------------------------------------------
--  DDL for Index PK_CARRERA
--------------------------------------------------------

  CREATE UNIQUE INDEX "12-1993"."PK_CARRERA" ON "12-1993"."CARRERA" ("COD_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MATRICULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "12-1993"."PK_MATRICULA" ON "12-1993"."ESTUDIANT" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UI_ESTUDIANT_CEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "12-1993"."UI_ESTUDIANT_CEDULA" ON "12-1993"."ESTUDIANT" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARRERA
--------------------------------------------------------

  ALTER TABLE "12-1993"."CARRERA" ADD CONSTRAINT "PK_CARRERA" PRIMARY KEY ("COD_CARRERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "12-1993"."CARRERA" MODIFY ("COD_CARRERA" NOT NULL ENABLE);
 
  ALTER TABLE "12-1993"."CARRERA" MODIFY ("DESC_CARRERA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANT
--------------------------------------------------------

  ALTER TABLE "12-1993"."ESTUDIANT" ADD CONSTRAINT "CK_SEXO" CHECK (SEXO IN ('M','F')) ENABLE;
 
  ALTER TABLE "12-1993"."ESTUDIANT" ADD CONSTRAINT "PK_MATRICULA" PRIMARY KEY ("MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "12-1993"."ESTUDIANT" MODIFY ("MATRICULA" NOT NULL ENABLE);
 
  ALTER TABLE "12-1993"."ESTUDIANT" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "12-1993"."ESTUDIANT" MODIFY ("APELLIDO" NOT NULL ENABLE);
 
  ALTER TABLE "12-1993"."ESTUDIANT" MODIFY ("COD_CARRERA" NOT NULL ENABLE);
 
  ALTER TABLE "12-1993"."ESTUDIANT" ADD CONSTRAINT "UI_ESTUDIANT_CEDULA" UNIQUE ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANT
--------------------------------------------------------

  ALTER TABLE "12-1993"."ESTUDIANT" ADD CONSTRAINT "FK_COD_CARRERA" FOREIGN KEY ("COD_CARRERA")
	  REFERENCES "12-1993"."CARRERA" ("COD_CARRERA") ENABLE;
